modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/LXGaming/Sledgehammer/issues"

[[mods]]
modId="sledgehammer"
version="@version@"
displayName="Sledgehammer"
displayURL="https://lxgaming.github.io/"
logoFile="sledgehammer.png"
credits="LX_Gaming"
authors="LX_Gaming"
description="Sledgehammer\nSource - https://github.com/LXGaming/Sledgehammer"