name: Java

on:
  create:
    tags: [ 'v*.*.*' ]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  java:
    name: Java
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup Gradle
      run: chmod +x gradlew
    - name: Build
      env:
        BUILD_NUMBER: ${{ github.run_number }}
      run: ./gradlew build --console=plain --refresh-dependencies
    - name: Setup Release
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: echo "release_name=${GITHUB_REPOSITORY#*/} ${GITHUB_REF_NAME}" >> $GITHUB_ENV
    - name: Release
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      uses: softprops/action-gh-release@v1
      with:
        files: ./build/libs/*.jar
        generate_release_notes: true
        name: ${{ env.release_name }}